--DROP TABLE IF EXISTS animal_task CASCADE;
--DROP TABLE IF EXISTS worker_task CASCADE;
--DROP TABLE IF EXISTS worker_role CASCADE;
--DROP TABLE IF EXISTS task CASCADE;
--DROP TABLE IF EXISTS animal CASCADE;
--DROP TABLE IF EXISTS worker CASCADE;
--DROP TABLE IF EXISTS equipment CASCADE;
--DROP TABLE IF EXISTS place CASCADE;
--DROP TABLE IF EXISTS role CASCADE;

CREATE TABLE animal_task
(
    animal_id BIGINT NOT NULL,
    task_id   BIGINT NOT NULL
);

CREATE TABLE task
(
    task_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    data        TIMESTAMP WITHOUT TIME ZONE,
    deadline    TIMESTAMP WITHOUT TIME ZONE,
    worker      BIGINT,
    equipment   BIGINT,
    task_status VARCHAR(255),
    CONSTRAINT pk_task PRIMARY KEY (task_id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_EQUIPMENT FOREIGN KEY (equipment) REFERENCES equipment (equipment_id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_WORKER FOREIGN KEY (worker) REFERENCES worker (worker_id);

ALTER TABLE animal_task
    ADD CONSTRAINT fk_anitas_on_animal FOREIGN KEY (animal_id) REFERENCES animal (animal_id);

ALTER TABLE animal_task
    ADD CONSTRAINT fk_anitas_on_task FOREIGN KEY (task_id) REFERENCES task (task_id);


CREATE TABLE worker
(
    worker_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login      VARCHAR(255),
    surname    VARCHAR(255),
    firstname  VARCHAR(255),
    patronymic VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_worker PRIMARY KEY (worker_id)
);

CREATE TABLE worker_role
(
    role_id   BIGINT NOT NULL,
    worker_id BIGINT NOT NULL
);

ALTER TABLE worker_role
add constraint pk_worker_role primary key (role_id, worker_id);
ALTER TABLE worker_role
    ADD CONSTRAINT fk_worrol_on_role FOREIGN KEY (role_id) REFERENCES role (role_id);

ALTER TABLE worker_role
    ADD CONSTRAINT fk_worrol_on_worker FOREIGN KEY (worker_id) REFERENCES worker (worker_id);

CREATE TABLE role
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

CREATE TABLE place
(
    place_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    place_name  VARCHAR(255),
    temperature BIGINT,
    humidity    BIGINT,
    CONSTRAINT pk_place PRIMARY KEY (place_id)
);

CREATE TABLE equipment
(
    equipment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_type   VARCHAR(255),
    equipment_name   VARCHAR(255),
    equipment_status VARCHAR(255),
    CONSTRAINT pk_equipment PRIMARY KEY (equipment_id)
);

alter table equipment alter column equipment_type type VARCHAR(255);

CREATE TABLE animal
(
    animal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(255),
    gender        VARCHAR(255),
    birthday      TIMESTAMP WITHOUT TIME ZONE,
    health_status VARCHAR(255),
    place         BIGINT,
    CONSTRAINT pk_animal PRIMARY KEY (animal_id)
);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_PLACE FOREIGN KEY (place) REFERENCES place (place_id);

insert into role (role_id, role_name) values (1, 'ROLE_ADMIN'), (2, 'ROLE_USER');
insert into equipment (equipment_type, equipment_name, equipment_status) values ('FORKLIFT', 'Caterpillar', 'FREE');
insert into equipment (equipment_type, equipment_name, equipment_status) values ('TRACK', 'Ford', 'FREE');
insert into equipment (equipment_type, equipment_name, equipment_status) values ('TRACK', 'Chevi', 'REPAIR');
update  equipment set equipment_type = 'TRUCK', equipment_name = 'Toyota Hilux', equipment_status = 'BUSY' where equipment.equipment_id = 4;

insert into place (place_name, temperature, humidity) values ('HLEV', 18, 60);
insert into place (place_name, temperature, humidity) values ('ZAGON', 18, 60);
insert into place (place_name, temperature, humidity) values ('VET_CABINET', 18, 60);
insert into place (place_name, temperature, humidity) values ('USADBA', 18, 60);
insert into place (place_name, temperature, humidity) values ('DVOR', 18, 60);
insert into place (place_name, temperature, humidity) values ('ANGAR', 18, 60);


truncate table role cascade ;